import numpy as np

def loadCameras( time=0, threshSurf=400, edgeLims=[100,200], t2occ=60 ):

    camera1 = {
        'number': 1,
        'port': 9301,
        'new': 1,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,
        'nFails': 0,
        'spots': [
            {
                'number': 1,
                'vertices': np.array(
                        [[   127,  392],
                         [   194,  389],
                         [   232,  222],
                         [   169,  242]]),
                'base_means': [149,144,131],
                'base_nEdges': 53,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'meanThresh': 15,
                'edgeThresh': 50,
                'keyThresh': 1,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 2,
                'vertices': np.array(
                        [[   285,  404],
                         [   534,  400],
                         [   451,  125],
                         [   314,  170]]),
                'base_means': [115,110,110],
                'base_nEdges': 575,
                'base_nKeys': 2,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 20,
                'edgeThresh': 150,
                'keyThresh': 20,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 3,
                'vertices': np.array(
                        [[ 595,   386],
                         [ 705,   384],
                         [ 701,   143],
                         [ 650,    83],
                         [ 494,    92]]),
                'base_means': [132,130,129],
                'base_nEdges': 675,
                'base_nKeys': 1,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 15,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera2 = {
        'number': 2,
        'port': 9002,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 4,
                'vertices': np.array(
                            [[ 220,   0],
                             [ 370,   0],
                             [ 400, 100],
                             [ 400, 224],
                             [ 220, 224]]),
                'base_means': [127,123,123],
                'base_nEdges': 6,
                'base_nKeys': 2,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 25,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 5,
                'vertices': np.array(
                            [[  40,  50],
                             [ 190,  20],
                             [ 175, 224],
                             [   0, 224],
                             [   0, 180]]),
                'base_means': [120,120,120],
                'base_nEdges': 1000,
                'base_nKeys': 55,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 200,
                'keyThresh': 15,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera3 = {
        'number': 3,
        'port': 9003,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 6,
                'vertices': np.array(
                            [[ 290,   0],
                             [ 380,   0],
                             [ 400,  40],
                             [ 400, 224],
                             [ 340, 224]]),
                'base_means': [101,102,101],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 7,
                'vertices': np.array(
                            [[ 130,  30],
                             [ 265,   0],
                             [ 310, 224],
                             [ 105, 224]]),
                'base_means': [121,122,122],
                'base_nEdges': 0,
                'base_nKeys': 20,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 8,
                'vertices': np.array(
                            [[   0,  50],
                             [ 100,  50],
                             [  80, 224],
                             [   0, 224]]),
                'base_means': [137,137,140],
                'base_nEdges': 175,
                'base_nKeys': 10,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 5,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera4 = {
        'number': 4,
        'port': 9004,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 9,
                'vertices': np.array(
                            [[ 325,  25],
                             [ 330,  25],
                             [ 400, 120],
                             [ 400, 165]]),
                'base_means': [118,120,120],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 2,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 10,
                'vertices': np.array(
                            [[ 190,  30],
                             [ 260,  30],
                             [ 370, 224],
                             [ 260, 224]]),
                'base_means': [119,122,122],
                'base_nEdges': 62,
                'base_nKeys': 1,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 1000,
                'keyThresh': 20,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 11,
                'vertices': np.array(
                            [[  40,  40],
                             [ 145,  40],
                             [ 170, 224],
                             [  40, 224]]),
                'base_means': [117,117,118],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 450,
                'keyThresh': 35,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera5 = {
        'number': 5,
        'port': 9005,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 12,
                'vertices': np.array(
                            [[ 330,   0],
                             [ 400,   0],
                             [ 400, 224],
                             [ 370, 224]]),
                'base_means': [99,101,103],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 60,
                'keyThresh': 0,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 13,
                'vertices': np.array(
                            [[ 130,  25],
                             [ 290,  25],
                             [ 330, 224],
                             [  90, 224]]),
                'base_means': [122,122,121],
                'base_nEdges': 280,
                'base_nKeys': 21,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 14,
                'vertices': np.array(
                            [[   0,  50],
                             [ 100,  50],
                             [  50, 224],
                             [   0, 224]]),
                'base_means': [126,123,123],
                'base_nEdges': 0,
                'base_nKeys': 1,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera6 = {
        'number': 6,
        'port': 9006,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 15,
                'vertices': np.array(
                            [[   0,  40],
                             [  30,  40],
                             [ 100, 170],
                             [   0, 170]]),
                'base_means': [121,118,118],
                'base_nEdges': 207,
                'base_nKeys': 3,
                'base_means': [114,113,113],
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 3,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 16,
                'vertices': np.array(
                            [[  85,  20],
                             [ 290,  20],
                             [ 235, 195],
                             [ 140, 195]]),
                'base_means': [113,115,115],
                'base_nEdges': 220,
                'base_nKeys': 15,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 20,
                'edgeThresh': 200,
                'keyThresh': 1,
                'detectionType': 'kem',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 17,
                'vertices': np.array(
                            [[ 400,   0],
                             [ 400,  85],
                             [ 350, 150],
                             [ 300, 155]]),
                'base_means': [123,125,125],
                'base_nEdges': 28,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 5,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 22,
                'vertices': np.array(
                            [[ 150, 200],
                             [ 275, 200],
                             [ 255, 230],
                             [ 155, 225]]),
                'base_means': [166,163,163],
                'base_nEdges': 122,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 2,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
        ]
    }

    camera7 = {
        'number': 7,
        'port': 9007,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 18,
                'vertices': np.array(
                            [[ 180, 110],
                             [ 295, 110],
                             [ 375, 224],
                             [ 175, 224]]),
                'base_means': [110,114,114],
                'base_nEdges': 82,
                'base_nKeys': 4,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 19,
                'vertices': np.array(
                            [[  50, 110],
                             [ 150, 110],
                             [ 150, 224],
                             [   0, 224],
                             [   0, 180]]),
                'base_means': [120,121,121],
                'base_nEdges': 72,
                'base_nKeys': 6,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 23,
                'vertices': np.array(
                            [[  80,  30],
                             [ 220,  30],
                             [ 220,  50],
                             [  80,  50]]),
                'base_means': [150,148,145],
                'base_nEdges': 350,
                'base_nKeys': 5,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 5,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
        ]
    }

    camera8 = {
        'number': 8,
        'port': 9008,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 20,
                'vertices': np.array(
                            [[ 260,  20],
                             [ 360,  20],
                             [ 400,  70],
                             [ 400, 224],
                             [ 275, 224],
                             [ 255,  50]]),
                'base_means': [99,99,99],
                'base_nEdges': 9,
                'base_nKeys': 3,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 21,
                'vertices': np.array(
                            [[  70,  25],
                             [ 170,  25],
                             [ 140, 224],
                             [   0, 224],
                             [   0, 130]]),
                'base_means': [105,105,105],
                'base_nEdges': 400,
                'base_nKeys': 21,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 150,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
        ]
    }

    camera9 = {
        'number': 9,
        'port': 9009,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 24,
                'vertices': np.array(
                            [[  80,  40],
                             [ 155,  30],
                             [  95, 170],
                             [  35, 165],
                             [  15, 120]]),
                'base_means': [138,137,135],
                'base_nEdges': 31,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 25,
                'vertices': np.array(
                            [[ 172,  30],
                             [ 260,  30],
                             [ 290, 100],
                             [ 145, 100]]),
                'base_means': [112,112,112],
                'base_nEdges': 11,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 26,
                'vertices': np.array(
                            [[ 300,  20],
                             [ 340,  20],
                             [ 400,  75],
                             [ 400, 160],
                             [ 370, 165]]),
                'base_means': [143,142,142],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
        ]
    }

    camera10 = {
        'number': 10,
        'port': 9300,
        'new': 1,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 27,
                'vertices': np.array(
                            [[  60,  35],
                             [ 140,  35],
                             [ 105, 130],
                             [   0, 130],
                             [   0, 105]]),
                'base_means': [145,145,145],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 28,
                'vertices': np.array(
                            [[ 270,  40],
                             [ 345,  40],
                             [ 400, 105],
                             [ 400, 170],
                             [ 325, 190]]),
                'base_means': [135,135,135],
                'base_nEdges': 0,
                'base_nKeys': 4,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera11 = {
        'number': 11,
        'port': 9011,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 36,
                'vertices': np.array(
                            [[  50,  75],
                             [ 105,  75],
                             [  50, 224],
                             [   0, 224],
                             [   0, 155]]),
                'base_means': [114,116,115],
                'base_nEdges': 92,
                'base_nKeys': 1,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 5,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 37,
                'vertices': np.array(
                            [[ 140,  75],
                             [ 245,  75],
                             [ 300, 224],
                             [ 120, 224]]),
                'base_means': [140,142,141],
                'base_nEdges': 100,
                'base_nKeys': 20,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 400,
                'keyThresh': 10,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 38,
                'vertices': np.array(
                            [[ 305,  90],
                             [ 350,  85],
                             [ 400, 145],
                             [ 400, 224],
                             [ 355, 224]]),
                'base_means': [110,113,112],
                'base_nEdges': 104,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 200,
                'keyThresh': 10,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 43,
                'vertices': np.array(
                            [[ 168,   2],
                             [ 200,   2],
                             [ 223,  30],
                             [ 159,  30]]),
                'base_means': [152,144,143],
                'base_nEdges': 72,
                'base_nKeys': 2,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 0,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera12 = {
        'number': 12,
        'port': 9012,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 33,
                'vertices': np.array(
                            [[  50, 105],
                             [ 125, 105],
                             [  85, 224],
                             [   0, 224],
                             [   0, 175]]),
                'base_means': [133,132,130],
                'base_nEdges': 111,
                'base_nKeys': 4,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 34,
                'vertices': np.array(
                            [[ 157, 100],
                             [ 270, 100],
                             [ 305, 224],
                             [ 120, 224]]),
                'base_means': [130,132,130],
                'base_nEdges': 600,
                'base_nKeys': 18,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 35,
                'vertices': np.array(
                            [[ 330, 100],
                             [ 370, 100],
                             [ 400, 135],
                             [ 400, 224],
                             [ 365, 224]]),
                'base_means': [114,115,114],
                'base_nEdges': 120,
                'base_nKeys': 5,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 5,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 44,
                'vertices': np.array(
                            [[ 300,   8],
                             [ 329,   9],
                             [ 380,  40],
                             [ 330,  40]]),
                'base_means': [130,123,127],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 75,
                'keyThresh': 2,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 45,
                'vertices': np.array(
                            [[ 240,   8],
                             [ 280,   8],
                             [ 307,  27],
                             [ 250,  27]]),
                'base_means': [97,97,100],
                'base_nEdges': 29,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 75,
                'keyThresh': 3,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 46,
                'vertices': np.array(
                            [[ 187,   5],
                             [ 230,   5],
                             [ 239,  20],
                             [ 182,  20]]),
                'base_means': [107,106,110],
                'base_nEdges': 3,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 20,
                'edgeThresh': 30,
                'keyThresh': 1,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera13 = {
        'number': 13,
        'port': 9013,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 29,
                'vertices': np.array(
                            [[   0,  60],
                             [  60,  50],
                             [  70,  75],
                             [  55, 140],
                             [  50, 224],
                             [   0, 224]]),
                'base_means': [144,138,135],
                'base_nEdges': 8,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 30,
                'vertices': np.array(
                            [[ 140,  55],
                             [ 280,  55],
                             [ 300, 224],
                             [ 115, 224]]),
                'base_means': [111,115,115],
                'base_nEdges': 300,
                'base_nKeys': 21,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 31,
                'vertices': np.array(
                            [[ 335,   0],
                             [ 375,   0],
                             [ 400,  65],
                             [ 400, 224],
                             [ 365, 224]]),
                'base_means': [138,139,137],
                'base_nEdges': 76,
                'base_nKeys': 5,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 10,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera14 = {
        'number': 14,
        'port': 9014,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 32,
                'vertices': np.array(
                            [[ 150, 130],
                             [ 280, 140],
                             [ 290, 224],
                             [ 105, 224]]),
                'base_means': [115,118,118],
                'base_nEdges': 90,
                'base_nKeys': 2,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 20,
                'keyThresh': 1,
                'detectionType': 'ke',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 47,
                'vertices': np.array(
                            [[ 270,   0],
                             [ 305,  10],
                             [ 330,  35],
                             [ 275,  25]]),
                'base_means': [150,145,150],
                'base_nEdges': 34,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 2,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 48,
                'vertices': np.array(
                            [[ 205,   0],
                             [ 250,   0],
                             [ 255,  25],
                             [ 190,  20]]),
                'base_means': [126,125,128],
                'base_nEdges': 89,
                'base_nKeys': 1,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 1,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 49,
                'vertices': np.array(
                            [[ 162,   0],
                             [ 190,   0],
                             [ 180,  20],
                             [ 160,  20]]),
                'base_means': [144,142,148],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 30,
                'keyThresh': 0,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    camera15 = {
        'number': 15,
        'port': 9015,
        'im_ts': time,
        'threshSurf': threshSurf,
        'edgeLims': edgeLims,       
        'nFails': 0,
        'spots': [
            {
                'number': 39,
                'vertices': np.array(
                            [[ 150, 130],
                             [ 280, 140],
                             [ 290, 224],
                             [ 105, 224]]),
                'base_means': [115,118,118],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 100,
                'keyThresh': 7,
                'detectionType': 'k',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 40,
                'vertices': np.array(
                            [[ 270,   0],
                             [ 305,  10],
                             [ 330,  35],
                             [ 275,  25]]),
                'base_means': [150,145,150],
                'base_nEdges': 34,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 2,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 41,
                'vertices': np.array(
                            [[ 205,   0],
                             [ 250,   0],
                             [ 255,  25],
                             [ 190,  20]]),
                'base_means': [126,125,128],
                'base_nEdges': 89,
                'base_nKeys': 1,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 50,
                'keyThresh': 1,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            },
            {
                'number': 42,
                'vertices': np.array(
                            [[ 162,   0],
                             [ 190,   0],
                             [ 180,  20],
                             [ 160,  20]]),
                'base_means': [144,142,148],
                'base_nEdges': 0,
                'base_nKeys': 0,
                'means': [0,0,0],
                'sigs': [0,0,0],
                'maxs': [0,0,0],
                'mins': [0,0,0],
                'mean': 0,
                'meanThresh': 10,
                'edgeThresh': 30,
                'keyThresh': 0,
                'detectionType': 'e',
                'timePresent': 0,
                'timeOccupied': 0,
                'occupationStartTime': time,
                'occupationEndTime': time,
                'occupationThresh': t2occ
            }
        ]
    }

    cameras = {1: camera1,
               2: camera2,
               3: camera3,
               4: camera4,
               5: camera5,
               6: camera6,
               7: camera7,
               8: camera8,
               9: camera9,
               10: camera10,
               11: camera11,
               12: camera12,
               13: camera13,
               14: camera14,
               15: camera15}
    
    return cameras
